include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    # Ignore generated and build artifacts
    - '**/*.mocks.dart'
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/generated_plugin_registrant.dart'
    - '**/build/**'
    - '**/.dart_tool/**'

linter:
  rules:
    - prefer_final_in_for_each
    - prefer_final_locals
